[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "docx>=0.2.4",
    "google-generativeai>=0.8.4",
    "olefile>=0.47",
    "requests>=2.32.3",
    "twitchio>=2.10.0",
]
